services:
  redis:
    image: redis:latest
    container_name: redis_meetime
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=
    command: ["redis-server", "--requirepass", ""]
  mongo:
    image: mongo:latest
    container_name: mongo_meetime
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: ["mongod", "--auth"]

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
