spring:
  redis:
    host: redis_meetime
    port: 6379
  mongodb:
    uri: mongodb://root:root@localhost:27017/meetime?authSource=admin

hubspot:
  client-id: "client_id"
  client-secret: "client_secret"
  redirect-uri: http://localhost:8080/auth/callback
  scopes: crm.objects.contacts.write%20crm.objects.contacts.read
